// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm0aaJfw-lmG9Tr8z7ejdSOBCFO1Q4tVA',
    appId: '1:439493964289:web:fe6a078cf3ba37956bc600',
    messagingSenderId: '439493964289',
    projectId: 'task-ass',
    authDomain: 'task-ass.firebaseapp.com',
    storageBucket: 'task-ass.appspot.com',
    measurementId: 'G-E7PYJP6FWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Xg-UUEOwFH3bd4VN5_Jmpp1HdcJqpCk',
    appId: '1:439493964289:android:39044b0e26d2ab846bc600',
    messagingSenderId: '439493964289',
    projectId: 'task-ass',
    storageBucket: 'task-ass.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtU5YYgx6x7mcY9HvcknMtJgalZA_BC_w',
    appId: '1:439493964289:ios:1d9cc89e3d582e856bc600',
    messagingSenderId: '439493964289',
    projectId: 'task-ass',
    storageBucket: 'task-ass.appspot.com',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtU5YYgx6x7mcY9HvcknMtJgalZA_BC_w',
    appId: '1:439493964289:ios:1d9cc89e3d582e856bc600',
    messagingSenderId: '439493964289',
    projectId: 'task-ass',
    storageBucket: 'task-ass.appspot.com',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm0aaJfw-lmG9Tr8z7ejdSOBCFO1Q4tVA',
    appId: '1:439493964289:web:63616718ffd71c206bc600',
    messagingSenderId: '439493964289',
    projectId: 'task-ass',
    authDomain: 'task-ass.firebaseapp.com',
    storageBucket: 'task-ass.appspot.com',
    measurementId: 'G-13V3H42YKY',
  );
}
